name: .NET Testing

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix: 
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['6.0']
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore EvilGiraffes.Tests
    - name: Build
      run: dotnet build EvilGiraffes.Tests --no-restore
    - name: Test
      run: dotnet test EvilGiraffes.Tests --no-build --verbosity normal
